#!/usr/bin/env bash
# This script uses dig and awk to print out the details of a domain and/or subdomain
#+in the format The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
# it takes in the domain name as first argument and subdomain name as second argument
# if only domain is provided it prints info about all subdomains of the domain

function get_records() {
    domain=$1
    subdomain=$2

    if [[ -z "$subdomain" ]]; then
        subdomains="www lb-01 web-01 web-02"
    else
        subdomains="$subdomain"
    fi

    for subdomain in $subdomains; do
        type_ip=$(dig A "$subdomain.$domain" | grep -A1 "ANSWER SECTION" | awk '{print $4,$5}' | tail -n1)
        if [[ -n "$type_ip" ]]; then
            type=$(awk '{print $1}' <<< "$type_ip")
            ip=$(awk '{print $2}' <<< "$type_ip")
            echo "The subdomain $subdomain is a $type record and points to $ip"
        fi
    done
}

if [[ "$#" -eq 1 ]]; then
    get_records $1;
elif [[ "$#" -eq 2 ]]; then
    get_records $1 $2;
elif [[ "$#" -eq 2 ]]; then
    echo "Usage: $0 [DOMAIN] [SUB_DOMAIN]"
    exit 1
fi
