#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)

if (( $# < 2 ));
then
    echo -n "The subdomain www "
    dig "www.$1" | grep -A1 'ANSWER SECTION' | tail -n -1 | awk '{print "is a "$4" record and points to " $5}'
    echo -n "The subdomain lb-01 "
    dig "lb-01.$1" | grep -A1 'ANSWER SECTION' | tail -n -1 | awk '{print "is a "$4" record and points to " $5}'
    echo -n "The subdomain web-01 "
    dig "web-01.$1" | grep -A1 'ANSWER SECTION' | tail -n -1 | awk '{print "is a "$4" record and points to " $5}'
    echo -n "The subdomain web-02 "
    dig "web-02.$1" | grep -A1 'ANSWER SECTION' | tail -n -1 | awk '{print "is a "$4" record and points to " $5}'
else
    echo -n "The subdomain $2 "
    dig "$2.$1" | grep -A1 'ANSWER SECTION' | tail -n -1 | awk '{print "is a "$4" record and points to " $5}'
fi
