#!/usr/bin/env bash
# scipt to transfer a file from our client to a server
# accepts 4 parameters:
# 1. path to file
# 2. server ip
# 3. username
# 4. path to ssh key

err_msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -lt 4 ]; then
    echo "$err_msg"
    exit 1
fi

# assign parameters to variables
file_name=$1
server_ip=$2
username=$3
ssh_key=$4

# use scp to transfer file from our client to a server's home directory
# check if scp command was successful
if scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_name" "$username@$server_ip:~/"; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
fi
