#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo "Holberton School" > "/var/www/html/index.html"
sudo service nginx reload
sudo service nginx restart
