#!/usr/bin/env bash
# configure web-02 to be identical to web-01, add header

sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /var/www/html
echo "Holberton School" >> "/var/www/html/index.html"
sudo sed -i "19i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx restart
