#!/usr/bin/env bash
# Displays numbers from 1-100, but:
# "FizzBuzz" if multiple of 3 and 5
# "Fizz" if multiple of 3
# "Buzz" if multiple of 5
# Otherwise diplays the number in a list format

for i in {1..100}; do
    if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
