#!/usr/bin/env bash
# Tells a story with the username, id, and home directory from /etc/passwd file

while read -r line; do
    IFS=":" read -ra fields <<< "$line"
    echo -n "The user ${fields[0]} is part of the ${fields[3]} gang, "
    echo -n "lives in ${fields[5]} and rides ${fields[6]}. "
    echo -n "${fields[2]}'s place is protected by the passcode ${fields[1]}, "
    echo "more info about the user here: ${fields[4]}"
done < /etc/passwd
