#!/usr/bin/env bash
# Loops from 10 times and display the following:
#+	"bad luck" for the 4th iteration
#+	"good luck" for the 8th iteration
#+	"Best School" for every other iteration

i=0

while [ $i -lt 10 ]; do
    case "$i" in
        "3")    echo "bad luck"     ;;
        "7")    echo "good luck"    ;;
        *)      echo "Best Schoo"   ;;
    esac

    (( i++ ))
done
