#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
#	on the 4th iteration, displays "4" and "bad luck from China"
#	on the 9th iteration, displays "9" and "bad luck from Japan"
#	on the 17th iteration, displays "17" and "bad luck from Italy"

i=1

while [ $i -lt 21 ]; do
    case $i in
        "4")    echo -e "$i\nbad luck from China"	;;
        "9")    echo -e "$i\nbad luck from Japan"	;;
        "17")   echo -e "$i\nbad luck from Italy"	;;
        *)      echo -e "$i"				        ;;
    esac
    (( i++ ))
done
