#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
# Displays the hours from 0-12 and minutes from 1-59

hours=0
minutes=1

echo "Hour: $hours"

while true; do
    echo "$minutes"
    if [ $hours -eq 12 ] && [ $minutes -eq 59 ]; then
        break
    fi
    if [ $minutes -eq 59 ]; then
        (( hours++ ))
        echo "Hour: $hours"
        minutes=0
    fi
    (( minutes++ ))
done
